export const CARD_NO_FILTER = "CARD_NO_FILTER";
export const CARD_IN_PROGRESS_FILTER = "CARD_IN_PROGRESS_FILTER";
export const CARD_COMPLETED_FILTER = "CARD_COMPLETED_FILTER";
export const CARD_TODAY_FILTER = "CARD_TODAY_FILTER";