export const SHOW_COMPLETION_SUCCESS_ALERT = "SHOW_COMPLETION_SUCCESS_ALERT";
export const HIDE_COMPLETION_SUCCESS_ALERT = "HIDE_COMPLETION_SUCCESS_ALERT";
export const SHOW_COMPLETION_ERROR_ALERT = "SHOW_COMPLETION_ERROR_ALERT";
export const HIDE_COMPLETION_ERROR_ALERT = "HIDE_COMPLETION_ERROR_ALERT";