export const FETCH_CARDS = "FETCH_CARDS";
export const CREATE_CARD = "CREATE_CARD";
export const DELETE_CARD = "DELETE_CARD";
export const EDIT_CARD_DESCRIPTION = "EDIT_CARD_DESCRIPTION";
export const EDIT_CARD_TERM = "EDIT_CARD_TERM";
export const COMPLETE_CARD = "COMPLETE_CARD";
export const COMPLETE_CARD_TERM = "COMPLETE_CARD_TERM";
export const CANCEL_CARD_TERM_COMPLETION = "CANCEL_CARD_TERM_COMPLETION";

export const CREATE_TASK = "CREATE_TASK";
export const EDIT_TASK = "EDIT_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const COMPLETE_TASK = "COMPLETE_TASK";
export const CANCEL_TASK_COMPLETION = "CANCEL_TASK_COMPLETION";